name: ai_fitness_app_2
description: "An AI-powered fitness app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Supabase
  supabase_flutter: ^2.3.4

  # Authentication
  google_sign_in: ^6.3.0

  # State management
  provider: ^6.1.1

  # Local storage
  shared_preferences: ^2.5.3

  # UI utilities
  flutter_svg: ^2.1.0
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.2.0+4
  intl: ^0.19.0

  # Image handling
  image_picker: ^1.0.7
  uuid: ^4.3.3
  percent_indicator: ^4.2.5
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/brands/trainova_v1.png"
  adaptive_icon_background: "#5D54C0" # Trainova brand color
  adaptive_icon_foreground: "assets/images/brands/trainova_v1.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/brands/
    - assets/images/icons/
