name: "Build"

on:
  pull_request:
    branches:
      - dev
      - test
  push:
    branches:
      - dev
      - test
      - main
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create a release"
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "temurin"
          java-version: "17"

      #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"

      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      #5 Create Local Properties
      - name: Create Local Properties
        run: |
          echo "flutter.sdk=/opt/hostedtoolcache/flutter/stable-3.29.3-x64" > android/local.properties

      #6 Build Debug APK
      - name: Build Debug APK
        run: flutter build apk --debug --no-tree-shake-icons

      #7 Upload Debug Artifacts
      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Debug-Releases
          path: |
            build/app/outputs/flutter-apk/app-debug.apk

      #8 Extract Version
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      #9 Check if Tag Exists
      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      #10 Modify Tag if it Exists
      - name: Modify Tag
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          new_version="${{ env.VERSION }}-build-${{ github.run_number }}"
          echo "VERSION=$new_version" >> $GITHUB_ENV
        
      #11 Create Release
      - name: Create Release
        if: github.event_name == 'push' || github.event.inputs.create_release == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-debug.apk"
          tag: v${{ env.VERSION }}
          name: "Trainova v${{ env.VERSION }} (Debug)"
          body: |
            Debug release of Trainova version ${{ env.VERSION }}
            
            ### What's New
            - Auto-update functionality
            - Bug fixes and performance improvements
            
            Note: This is a debug build for testing purposes.
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
