name: "Build"

on:
  pull_request:
    branches:
      - dev
      - test
  push:
    branches:
      - dev
      - test
      - main
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create a release"
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to properly check tags

      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "temurin"
          java-version: "17"

      #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"

      #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      #5 Create Local Properties
      - name: Create Local Properties
        run: |
          echo "flutter.sdk=/opt/hostedtoolcache/flutter/stable-3.29.3-x64" > android/local.properties

      #6 Setup keystore from secrets
      - name: Setup keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          echo "storeFile=../app/keystore.jks" > android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties

          # Display the SHA-1 fingerprint for Google OAuth verification
          keytool -list -v -keystore android/app/keystore.jks -alias ${{ secrets.KEY_ALIAS }} -storepass ${{ secrets.STORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} | grep "SHA1:"

          cat android/key.properties

      #7 Build Release APK
      - name: Build Release APK
        run: flutter build apk --release --no-tree-shake-icons

      #8 Upload Release Artifacts
      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release-APK
          path: |
            build/app/outputs/flutter-apk/app-release.apk

      #9 Extract Version
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Extracted version: $version"

      #10 Better Tag Existence Check
      - name: Check if Tag Exists
        id: check_tag
        run: |
          # Fetch all tags
          git fetch --tags

          # Check if tag exists using a more reliable method
          tag_name="v${{ env.VERSION }}"
          if git tag -l "$tag_name" | grep -q "$tag_name"; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
            echo "Tag $tag_name already exists"
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
            echo "Tag $tag_name does not exist"
          fi

      #11 Modify Version if Tag Exists
      - name: Modify Version if Tag Exists
        if: env.TAG_EXISTS == 'true'
        id: modify_version
        run: |
          original_version="${{ env.VERSION }}"
          new_version="${original_version}-build-${{ github.run_number }}"
          echo "Modified version from $original_version to $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV

          # Double-check that the new tag doesn't exist
          if git tag -l "v$new_version" | grep -q "v$new_version"; then
            echo "Error: Modified tag v$new_version also exists!"
            exit 1
          else
            echo "Modified tag v$new_version is available"
          fi

      #12 Create Release
      - name: Create Release
        if: github.event_name == 'push' || github.event.inputs.create_release == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v${{ env.VERSION }}
          name: "Trainova v${{ env.VERSION }}"
          body: |
            Release of Trainova version ${{ env.VERSION }}

            ### What's New
            - Auto-update functionality
            - Bug fixes and performance improvements
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
